Task_1_1_1
polyachkov/OOP pull request #3
Opened 2023-09-20 19:51 UTC by polyachkov

2023-09-23 07:20 UTC, BIGNIKi requested changes

2023-09-23 07:20 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/org/example/HeapSort.java
> +    public static void heapify(int arr[], int n, int i) {
Представь, что мы делаем из нашего кода пакет, который потом предоставим клиентам.
Они увидят, что класс HeapSort предоставляет публичную реализацию некоего метода heapify, printArray и heapsort. Клиент, который получил класс HeapSort ожидает от класса лишь одного: функциональность сортировки, при том именно пирамидальной сортировки.
Действительно ли метод heapify должен быть публичным? Какую роль он несёт для того, кто использует этот класс?
Могу точно сказать, что heapify - является деталью реализации сортировки в данном случае и предполагается, что данные метод будет применяться исключительно внутри класса HeapSort.
Что касается метода printArray - выглядит как некоторый вспомогательный метод, слабо относящийся к сущности пирамидальной сортировки. Если в нем есть необходимость, его можно вынести в отдельный класс (e.g. Util), где ты хочешь хранить некоторые вспомогательные методы или же просто вытащить его в Main.

2023-09-23 07:20 UTC, BIGNIKi commented on Task_1_1_1/src/test/java/HeapSortTest.java
> +    public void testHeapify() {
Когда сделаешь Heapify приватным, тестировать его не нужно, т.к. всё, что является деталью реализации - не нуждается в тестировании. Другими словами, тестируя публичные методы своих классов, ты неявно тестируешь и детали реализации.
Если интересно, можно почитать это https://www.baeldung.com/java-unit-test-private-methods

2023-09-23 07:20 UTC, BIGNIKi commented on Task_1_1_1/src/test/java/HeapSortTest.java
> +    public void testEmptyArray() {
Не заставляю, но можно еще написать тест, который генерирует, например, около сотни тысяч чисел и прогоняет через твою сортировку. Сравнивать результат своей сортировки можно с сортировкой, которая уже определена в классе Arrays (Arrays.sort(...)).

2023-09-23 07:20 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/org/example/Main.java
> +    public static void main(String args[])
Ещё, по заданию, нужно написать bat/shell скрипт, который у тебя скомпилирует .class файлы, сгенерирует javadoc и исполнит Main класс.

2023-09-23 10:07 UTC, polyachkov commented on Task_1_1_1/src/main/java/org/example/HeapSort.java
> +    public static void heapify(int arr[], int n, int i) {
Понял спасибо. А что делать с тестировкой класса Main? Получается так что у меня задача из-за этого по критериям не проходит (80% покрытия)
Замечания увидел, поправлю

2023-09-23 10:14 UTC, BIGNIKi commented on Task_1_1_1/src/main/java/org/example/HeapSort.java
> +    public static void heapify(int arr[], int n, int i) {
Как и договорились на семинарах: на ту статистику, которую сгенерировал jacoco, я смотреть не буду, так как она крайне не показательна. Тесты надо писать на то, что действительно имеет смысл тестировать. Класс Main в тестировании у тебя не нуждается.

2023-09-27 11:46 UTC, BIGNIKi commented on Task_1_1_1/scipt.sh
> +read -p "Press enter to continue"
Лайк за read 👍

2023-09-27 11:54 UTC, BIGNIKi requested changes

2023-09-27 11:54 UTC, BIGNIKi commented on Task_1_1_1/src/test/java/HeapSortTest.java
> +        System.out.println(expected);
Зачем выводишь на консоль ссылки на массивы?

2023-09-27 11:54 UTC, BIGNIKi commented on Task_1_1_1/src/test/java/HeapSortTest.java
> +        int[] expected = new int[100000];
Зачем выделять память под 100000 int`ов и под массив. если буквально следующим выражением, ты ссылку, которая лежит в expected перезапишешь, а выделенная память так и останется выделенной и никому не нужной?
Можно просто в 51-ой строке написать: var expected = Arrays.copyOf(arr, 100000);
И всё, никаких лишних выделений.

2023-10-04 12:29 UTC, BIGNIKi approved these changes
Задачу принял

2023-10-04 12:29 UTC, BIGNIKi commented on Task_1_1_1/javadoc/allclasses-index.html
> +<!DOCTYPE HTML>
Папку javadoc нужно по-хорошему в .gitignore добавить, т.к. в репозитории она не нужна. Мы можем в любой момент через батник её сгенерировать.

2023-10-04 12:30 UTC, BIGNIKi commented
На будущее хочу сказать, что давай всё-таки codestyle, который нам навязывает github actions соблюдать.
![image](https://github.com/polyachkov/OOP/assets/91887896/63196bdf-1b80-4e64-83d3-f0fc6efdbaef)

2023-10-12 19:34 UTC, merged