Task_1_3_1
polyachkov/OOP pull request #6
Opened 2023-11-16 16:44 UTC by polyachkov

2023-11-22 07:46 UTC, BIGNIKi requested changes

2023-11-22 07:46 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/org/example/SubStringsFinder.java
> +            BufferedReader bufRead = new BufferedReader(fr);
Давай еще сделаешь чтение файла из ресурсов. Полезно будет разобраться, что такое ресурсы в джаве, где ждет их gradle и что gradle с ними делает при сборке.

2023-11-22 07:46 UTC, BIGNIKi commented on Task_1_3_1/src/test/java/org/example/SubStringFinderTest.java
> +    public void test() throws IOException {
Сделай еще тестовый метод, который генерит большой файл (15-20 гигов), ищет в нем подстроку (какую-нибудь небольшую, которая находится в самом конце файла). Также программно удалить этот файл. (как junit тест его не делай, кто знает как на это github workflow отреагирует)

2023-11-22 07:46 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/org/example/SubStringsFinder.java
> +            BufferedReader bufRead = new BufferedReader(fr);
Открыть открыл, а закрыть не закрыл. Классы, которые реализуют интерфейс Closeable нужно закрывать.
Закрой его тоже через конструкцию try with resources

2023-11-22 07:46 UTC, BIGNIKi commented on Task_1_3_1/test.txt
> +Hello my friend. I have a problem with brbrbrbrbr, help br, br, helbrbrbrbr...
Можно еще тестов добавить: на русских символах, на китайских и ещё иероглифов каких-нибудь.

2023-11-22 07:46 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/org/example/SubStringsFinder.java
> +            String buffer1 = readBlock(bufRead, subStringLength);
Кажется, это не лучший подход. Если подстрока - два символа, мы постоянно считываем блоки по два символа, делаем постоянные конкаты, бегаем по маленьким подстрокам...
Читать сразу порядка нескольких МБ в буффер было бы куда практичней, тем более для большого файла.
Сейчас есть чувство, что если у нас будет файл гигов на 8 + в конце подстрока длинной 2 символа, искать её мы будем долго.

2023-11-22 15:36 UTC, polyachkov commented on Task_1_3_1/src/main/java/org/example/SubStringsFinder.java
> +            BufferedReader bufRead = new BufferedReader(fr);
Я почитал про эту конструкцию - она же как раз и закрывает файл сама, нет?

2023-11-22 15:38 UTC, polyachkov commented on Task_1_3_1/src/main/java/org/example/SubStringsFinder.java
> +            String buffer1 = readBlock(bufRead, subStringLength);
Тут идея в том, что UTF-8 сложновато читать буффером по несколько мб, у меня лично не вышло сделать чтобы всё нормально работало с русскими буквами, потому что оно не понимает где 1 символ это 4 байта, а где 1 байт (как я понял)

2023-11-22 15:39 UTC, polyachkov commented on Task_1_3_1/src/main/java/org/example/SubStringsFinder.java
> +            String buffer1 = readBlock(bufRead, subStringLength);
Можно конечно сделать фиксированную минимальную длинну буфера, не спорю

2023-11-27 14:09 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/org/example/SubStringsFinder.java
> +            BufferedReader bufRead = new BufferedReader(fr);
BufferedReader тоже реализует интерфейс Closeable. А ты его не закрываешь.

2023-11-27 14:12 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/org/example/SubStringsFinder.java
> +            String buffer1 = readBlock(bufRead, subStringLength);
С Charset`ами разбирался? Они как раз должны помочь тебе подружиться с UTF-8

2023-11-27 15:59 UTC, polyachkov commented on Task_1_3_1/src/main/java/org/example/SubStringsFinder.java
> +            BufferedReader bufRead = new BufferedReader(fr);
Уххх... Понял

2023-11-27 16:00 UTC, polyachkov commented on Task_1_3_1/src/main/java/org/example/SubStringsFinder.java
> +            String buffer1 = readBlock(bufRead, subStringLength);
Вот как раз понял как работает вся эта канитель. Вопрос - как быстро должен работать код на файле 10-15гб?

2023-12-02 04:17 UTC, BIGNIKi approved these changes

2023-12-02 04:17 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/org/example/SubStringFinder.java
> +            if ((c = bufRead.read()) != -1) {
Читать по одному символу - плохо

2023-12-02 04:17 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/org/example/SubStringFinder.java
> +            String buffer1 = readBlock(bufRead, 1024L, charset);
Длину слова не констнтной сделать

2023-12-02 04:17 UTC, BIGNIKi commented on Task_1_3_1/src/main/java/org/example/SubStringFinder.java
> +                    result.addAll(checkBlock(buffer2.concat(newBlock), subString, startBlock));
Если лепишь строки в цикле, то через StringBuilder

2024-01-27 14:44 UTC, merged